Add enry functions (#140)
* added enry_detect_language

First of many. Pushing for review. How's it look?

* updated changes to function file

forgot to save the file, so these didn't get pushed

* update to error handling

* added return

* added all enry funcitons

Problem: IsTest won't register for some reason(EnryIsTest doesn't show under registered objects, "make" returns error: "tables/tables.go:63:31: undefined: enry.EnryIsTest")

* commented EnryIsTest out for now

* modified directory, minor if statement changes

* updated tests for each function

enry_is_binary needs work

* spelled enry correctly

* updated enry_is_binary_test.go

input filecontents not filepath now

* some formatting fixes

* add some documentation to the README

Co-authored-by: Patrick DeVivo <patrick.devivo@gmail.com>